Refactor CachedMeta, remove FieldsMeta
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases